<?php

const GLOBAL_STR_CONSTANT = 'GLOBAL_STR_CONSTANT';
const GLOBAL_INT_CONSTANT = 42;
const GLOBAL_FLOAT_CONSTANT = 3.14159;
const GLOBAL_BOOL_CONSTANT = true;

class MyClass {
    const CLASS_STR_CONSTANT = 'CLASS_STR_CONSTANT';
    const CLASS_INT_CONSTANT = 100;
}
