CONFIG_EDITOR_YML = "config_auditor.yml"
CONFIG_RULES_YML = "config_rules.yml"
SOFTWARE_NAME = "SAST Results Viewer"

# Auditor Key
NODE_KEY = "vuln_hash"
MANUAL_AUDIT = "manual_audit"
全部风险 = "全部风险"
全部类型 = "全部类型"
智能验证 = "智能验证"
人工验证 = "人工验证"

文件视图 = "文件视图"
风险视图 = "风险视图"

# Editor
PROJECT = "project"
EDITORS = "editors"
SOURCE_ROOT = "source_root"
ANALYSE_FILE = "analyse_file"
FULL_PATH = "full_path"
EXE_S = "exe"
ARGS_S = "args"
ENABLED = "enabled"
EDITOR_NAME = "name"

# 　Cache FIlE Key
CACHE_RESULT = "result"
CACHE_UPDATE = "last_update"

# AI Verify key
ORIGINAL = "original"
ERROR_S = "error"
PARSED = "parsed"
PROMPT = "prompt"
VERIFY = "verify"
RESPONSE = "response"
BECAUSE = "because"
HTTP_POC = "http_poc"
SENSITIVE = "sensitive"
EXPLAIN = "explain"
REPAIR = "repair"

# RE RUle File Key
LANGUAGES = "languages"
LANGUAGE = "language"
VULNERABILITIES = "vulnerabilities"
VULNERABILITY = "vulnerability"
SEVERITY = "severity"
IGNORE_CASE = "ignore_case"
LOADED = "loaded"
CONTEXT_NEED = "context_need"
CONTEXT_BEFORE = "context_before"
CONTEXT_AFTER = "context_after"
PATTERNS = "patterns"
PATTERN = "pattern"
DESCRIPTION = "description"
SAMPLE_CODE = "sample_code"
RULE_NAME = "name"
MATCH = "match"
CONTEXT = "context"
LINE_NUMBER = "line_number"
FILE_S = "file"
RELATED_SUFFIXES = "related_suffixes"
